spring:
  application:
    name: petoria
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: false
    show-sql: false
  jjwt:
    duration: 3000000
    secret: ${JJWT_SECRET}
  flyway:
    enabled: true
    locations: classpath:db/migration
  logging:
    level:
      org.springframework.security: DEBUG
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB